image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
    - npm install
    - npx tailwindcss -i ./src/input.css -o ./src/app.css
    - npm run build
    - mkdir public
    - mv output/* public
  artifacts:
    paths:
      - public
  only:
    - main